### ISSUE TITLE
Replace Tailwind with a future-ready CSS design system

### ISSUE THREAD

**Issue by MaybeThisIsRu** [MaybeThisIsRu/smix-eleventy-starter#22]
TailwindCSS recently got a new major release. We should upgrade soon.

**Comment by hirusi** [comment]
To-do sketch:

- [ ] Remove tailwind v1 from dependencies
- [ ] Install the compatibility build of tailwind v2
- [ ] Remove purgecss dependency and workflow (tailwind v2 includes it in core)
- [ ] Update how dark mode is handled
  - [ ] Remove the custom dark mode implementation (`dm` screen type)
  - [ ] Provide a custom media query for dark mode (so that it can be used in the CSS files easily)
  - [ ] Update templates to use the Tailwind v2 built-in dark mode prefix: `dark:`

**Comment by hirusi** [comment]
I'll try and finish this in the coming weeks.

**Comment by hirusi** [comment]
I'll probably remove Tailwind entirely from the project. Time to invest in [Every Layout](https://every-layout.dev) perhaps?

**Comment by hirusi** [comment]
- [ ] Media queries using [custom media](https://github.com/postcss/postcss-custom-media).
  - [ ] Replace dark mode
  - [ ] Replace large
  - [ ] Replace xs, sm, md
- [ ]

**Comment by hirusi** [comment]
This is inspectable on the `main` branch now -- however those last two todos remain from the previous comment.
